# Generated by Django 4.1.7 on 2023-02-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.PositiveIntegerField(default=1, verbose_name='Звезды'),
        ),
    ]
